version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: proteus-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app/backend
      - ./proteus:/app/proteus
    networks:
      - proteus-network
    command: python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proteus-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - proteus-network
    environment:
      - REACT_APP_API_URL=http://backend:8000

networks:
  proteus-network:
    driver: bridge